### PR TITLE
Fix write_enable commands and method.

### PR DESCRIPTION
**Pull request by hesee**
-This only has effect if sector protection enabled.

### CODE REVIEW

**Comment by hesee** [comment]
@marcuschangarm @geky could you check this?

**Comment by geky** [comment]
Ah good catch :+1: 

@marcuschangarm, does this look correct to you?

**Review by geky — APPROVED** [review]

**Comment by marcuschangarm** [comment]
Yep looks good! Thank you!

**Comment by geky** [comment]
@hesee thanks for the pr!

**Pull request merged**
