### PR TITLE
Increment erased block count in erase loop

### PR DESCRIPTION
**Pull request by hesee**
Erase() only erases one block. It looks like "erased" variable is erroneously decremented instead of increment. Underflows at first loop iteration.

#6

### CODE REVIEW

**Comment by geky** [comment]
@marcuschangarm, does this look good to you?

**Review by marcuschangarm — APPROVED** [review]

**Comment by marcuschangarm** [comment]
Looks good! I'm concerned how it got into that state though. I had it running the file system tests locally which means I must have pushed the wrong branch somehow so who knows what else is missing? 😨

**Comment by geky** [comment]
Sounds good to me, @marcuschangarm, I don't think many filesystem operations need erase to erase more than one block. Though it is an issue if you erase the entire block device or something.

@hesee, Thanks for the contribution!

**Comment by marcuschangarm** [comment]
> I don't think many filesystem operations need erase to erase more than one block. 

Ah, ok! That's more comforting then.

**Pull request merged**
